const resources = [
    { name: "Google Scholar", link: "https://scholar.google.com/" },
    { name: "ScienceDirect", link: "https://www.sciencedirect.com/" },
    { name: "PubChem", link: "https://pubchem.ncbi.nlm.nih.gov/" },
    { name: "Royal Society of Chemistry", link: "https://www.rsc.org/" },
    { name: "ChemSpider", link: "http://www.chemspider.com/" },
    { name: "American Chemical Society", link: "https://www.acs.org/" },
    { name: "Wiley Online Library", link: "https://onlinelibrary.wiley.com/" },
    { name: "SpringerLink Chemistry", link: "https://www.springer.com/gp/chemistry" },
    { name: "JSTOR Chemistry", link: "https://www.jstor.org/subject/chemistry" },
    { name: "Chemistry World", link: "https://www.chemistryworld.com/" },
    { name: "Cambridge University Press Chemistry", link: "https://www.cambridge.org/core/what-we-publish/chemistry" },
    { name: "Taylor & Francis Chemistry", link: "https://www.tandfonline.com/action/showPublications?category=57040438" },
    { name: "MDPI Open Access Journals", link: "https://www.mdpi.com/journal/molecules" },
    { name: "Nature Chemistry", link: "https://www.nature.com/nchem/" },
    { name: "Science Magazine", link: "https://www.sciencemag.org/topic/chemistry" },
    { name: "Chemistry LibreTexts", link: "https://chem.libretexts.org/" },
    { name: "Organic Chemistry Portal", link: "https://www.organic-chemistry.org/" },
    { name: "ChemGuide", link: "https://www.chemguide.co.uk/" },
    { name: "ChemCollective", link: "http://chemcollective.org/" },
    { name: "Chem1 Virtual Textbook", link: "http://www.chem1.com/" },
    { name: "National Center for Biotechnology Information", link: "https://www.ncbi.nlm.nih.gov/" },
    { name: "ACS Publications", link: "https://pubs.acs.org/" },
    { name: "IOPscience Chemistry", link: "https://iopscience.iop.org/journalList/chemistry" },
    { name: "ChemRxiv", link: "https://chemrxiv.org/" },
    { name: "arXiv Chemistry", link: "https://arxiv.org/list/chem/new" },
    { name: "SciFinder", link: "https://scifinder.cas.org/" },
    { name: "Chemistry Stack Exchange", link: "https://chemistry.stackexchange.com/" },
    { name: "Khan Academy Chemistry", link: "https://www.khanacademy.org/science/chemistry" },
    { name: "Coursera Chemistry", link: "https://www.coursera.org/courses?query=chemistry" },
    { name: "edX Chemistry", link: "https://www.edx.org/course/subject/chemistry" },
    { name: "FutureLearn Chemistry", link: "https://www.futurelearn.com/subjects/science-engineering-and-maths-courses/chemistry" },
    { name: "MIT OpenCourseWare Chemistry", link: "https://ocw.mit.edu/courses/chemistry/" },
    { name: "OpenStax Chemistry", link: "https://openstax.org/subjects/chemistry" },
    { name: "BioMed Central Chemistry", link: "https://www.biomedcentral.com/journals/chemistry" },
    { name: "Chemistry Europe", link: "https://chemistry-europe.onlinelibrary.wiley.com/" },
    { name: "Beilstein Journal of Organic Chemistry", link: "https://www.beilstein-journals.org/bjoc" },
    { name: "ChemPapers", link: "https://chempapers.com/" },
    { name: "Chemistry Resources by LibreTexts", link: "https://chem.libretexts.org/" },
    { name: "Plos Chemistry", link: "https://journals.plos.org/plosone/browse/chemistry" },
    { name: "ChemEd X", link: "https://www.chemedx.org/" },
    { name: "ERIC Chemistry Resources", link: "https://eric.ed.gov/?q=chemistry" },
    { name: "Sci-Hub", link: "https://sci-hub.se/" },
    { name: "Open Access Chemistry", link: "https://www.doabooks.org/" },
    { name: "Chemical Engineering Journal", link: "https://www.journals.elsevier.com/chemical-engineering-journal" },
    { name: "ChemWeb", link: "http://www.chemweb.com/" },
    { name: "ChemView", link: "https://chemview.epa.gov/chemview" },
    { name: "ChemTK", link: "http://chem.tk/" },
    { name: "ChemBlink", link: "http://www.chemblink.com/" },
    { name: "ChemSpider SyntheticPages", link: "https://cssp.chemspider.com/" },
    { name: "Chempedia", link: "https://chempedia.com/" },
    // Add 50 more resources here
    { name: "BioOne Complete", link: "https://bioone.org/" },
    { name: "Google Books Chemistry", link: "https://books.google.com/" },
    { name: "ERIC - Institute of Education Sciences", link: "https://eric.ed.gov/" },
    { name: "Chemistry Reference", link: "https://chemistryreference.com/" },
    { name: "Materials Project", link: "https://materialsproject.org/" },
    { name: "American Association for the Advancement of Science", link: "https://www.aaas.org/" },
    { name: "PerkinElmer Informatics", link: "https://www.perkinelmer.com/category/informatics" },
    { name: "ChemDraw", link: "https://www.perkinelmer.com/category/chemdraw" },
    { name: "Thermo Fisher Scientific", link: "https://www.thermofisher.com/" },
    { name: "Sigma-Aldrich", link: "https://www.sigmaaldrich.com/" },
    { name: "Nature Reviews Chemistry", link: "https://www.nature.com/natrevchem/" },
    { name: "Bioline International", link: "http://www.bioline.org.br/" },
    { name: "Chemical Society Reviews", link: "https://pubs.rsc.org/en/journals/journal/cs" },
    { name: "Inorganic Chemistry", link: "https://pubs.acs.org/journal/inocaj" },
    { name: "Journal of Organic Chemistry", link: "https://pubs.acs.org/journal/joceah" },
    { name: "Journal of Physical Chemistry", link: "https://pubs.acs.org/journal/jpcafh" },
    { name: "Chemistry Resources by CK-12", link: "https://www.ck12.org/chemistry/" },
    { name: "Chemistry LibreTexts", link: "https://chem.libretexts.org/" },
    { name: "Chemistry.com", link: "https://www.chemistry.com/" },
    { name: "Labster", link: "https://www.labster.com/" },
    { name: "Molecule of the Month", link: "https://www.chm.bris.ac.uk/motm/motm.htm" },
    { name: "Chemistry Olympiad", link: "https://www.chemistryolympiad.org/" },
    { name: "Chemistry TV", link: "https://www.chemistrytv.com/" },
    { name: "National Chemical Database Service", link: "https://www.chemspider.com/" },
    { name: "ChemEngOnline", link: "https://www.chemengonline.com/" },
    { name: "Science Magazine - Chemistry", link: "https://www.sciencemag.org/topic/chemistry" },
    { name: "The Journal of Chemical Physics", link: "https://aip.scitation.org/journal/jcp" },
    { name: "Journal of Chemical Theory and Computation", link: "https://pubs.acs.org/journal/jctcce" },
    { name: "Chemistry Central Journal", link: "https://chemistrycentralj.springeropen.com/" },
    { name: "Journal of Medicinal Chemistry", link: "https://pubs.acs.org/journal/jmcmar" },
    { name: "International Journal of Chemical Kinetics", link: "https://onlinelibrary.wiley.com/journal/10974639" },
    { name: "Chemical Reviews", link: "https://pubs.acs.org/journal/chreay" },
    { name: "Analytical Chemistry", link: "https://pubs.acs.org/journal/ancham" },
    { name: "Environmental Science & Technology", link: "https://pubs.acs.org/journal/esthag" },
    { name: "Journal of the American Chemical Society", link: "https://pubs.acs.org/journal/jacsat" },
    { name: "Journal of Chemical Education", link: "https://pubs.acs.org/journal/jceda8" },
    { name: "Annual Review of Physical Chemistry", link: "https://www.annualreviews.org/journal/pchem" },
    { name: "International Journal of Quantum Chemistry", link: "https://onlinelibrary.wiley.com/journal/1097461x" },
    { name: "Journal of Chemical Research", link: "https://journals.sagepub.com/home/jcr" },
    { name: "Chemical Communications", link: "https://pubs.rsc.org/en/journals/journal/cc" },
    { name: "Current Opinion in Chemical Biology", link: "https://www.journals.elsevier.com/current-opinion-in-chemical-biology" },
    { name: "Chemistry and Biology", link: "https://www.cell.com/chemistry-biology" },
    { name: "Chemistry: A European Journal", link: "https://onlinelibrary.wiley.com/journal/15213765" },
    { name: "Molecular Physics", link: "https://www.tandfonline.com/toc/tmpb20/current" },
    { name: "Physical Chemistry Chemical Physics", link: "https://pubs.rsc.org/en/journals/journal/pp" },
    { name: "Journal of the Chemical Society, Faraday Transactions", link: "https://pubs.rsc.org/en/journals/journal/faraday" },
    { name: "Chemical Biology & Drug Design", link: "https://onlinelibrary.wiley.com/journal/16109981" },
    { name: "Journal of Chemical Theory and Computation", link: "https://pubs.acs.org/journal/jctcce" },
    { name: "Journal of Coordination Chemistry", link: "https://www.tandfonline.com/toc/gcoc20/current" },
    { name: "Canadian Journal of Chemistry", link: "https://www.nrcresearchpress.com/journal/cjc" },
    { name: "Journal of Organometallic Chemistry", link: "https://www.journals.elsevier.com/journal-of-organometallic-chemistry" },
    { name: "Chemical Engineering Science", link: "https://www.journals.elsevier.com/chemical-engineering-science" },
    { name: "Computational and Theoretical Chemistry", link: "https://www.journals.elsevier.com/computational-and-theoretical-chemistry" },
    { name: "The Journal of Physical Chemistry A", link: "https://pubs.acs.org/journal/jpcafh" },
    { name: "The Journal of Physical Chemistry B", link: "https://pubs.acs.org/journal/jpcbfk" },
    { name: "The Journal of Physical Chemistry C", link: "https://pubs.acs.org/journal/jpccck" },
    { name: "Chemical Reviews", link: "https://pubs.acs.org/journal/chreay" },
    { name: "Journal of Chemical Research", link: "https://journals.sagepub.com/home/jcr" },
    { name: "International Journal of Chemical Sciences", link: "https://www.ijcsc.com/" },
    { name: "International Journal of Chemical Engineering", link: "https://www.hindawi.com/journals/ijce/" },
    { name: "Journal of Chemical Physics", link: "https://aip.scitation.org/journal/jcp" },
    { name: "Chemical Engineering Journal", link: "https://www.journals.elsevier.com/chemical-engineering-journal" },
    { name: "Journal of Chemical Theory and Computation", link: "https://pubs.acs.org/journal/jctcce" },
    { name: "Journal of the Chemical Society", link: "https://www.tandfonline.com/toc/gchm20/current" }
];

const resourceContainer = document.getElementById('resourceContainer');

resources.forEach(resource => {
    const listItem = document.createElement('li');
    const link = document.createElement('a');
    
    link.href = resource.link;
    link.textContent = resource.name;
    link.target = "_blank";
    
    listItem.appendChild(link);
    resourceContainer.appendChild(listItem);
});
